apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170408536
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170408536
    app.kubernetes.io/part-of: test-app-170408536
  name: go-170408536
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170408536
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170408536
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/vysmeyvs-tenant/test-app-170408536/go-170408536@sha256:76edde296ee59ccc865686a35d5e7de65d3b0254fdfd62a662f4a4f64bc7958d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
